# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "test01" do |test01|
    test01.vm.box = "jeqo/centos7-ansible"

    test01.vm.network "forwarded_port", guest: 5600, host: 5600

    test01.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = "512"
    end

    test01.vm.provision "ansible" do |ansible|
      ansible.playbook = "main.yml"
      ansible.galaxy_role_file = "roles.yml"
    end
  end
end
